monitor = WL-1, 1152x648, 0x0, 1 # this is for testing in 1366x768 display, later will be "monitor = , preferred, auto, 1" if ok

general {
  col.active_border = rgb(ff0000) # red for testing
  border_size = 1
}

# Source Hyprland Module
source = ~/arch-hyprlean/dotfiles/hypr/configs/keybindings.conf

