monitor = WL-1, 1152x648, 0x0, 1 # this is for testing in 1366x768 display, later will be "monitor = , preferred, auto, 1" if ok
$mainMod = ALT # after testing, change to SUPER
bind = $mainMod, Q, exec, foot
bind = $mainMod, M, exit

general {
  col.active.border = rgb(ff0000) # red for testing
  border_size = 4
  }
