# Default App
$terminal 	= foot
$browser 	= firefox
$fileManager = dolphin
$menu 		= fuzzel

# Visual Setting
$gapsIn 	= 2
$gapsOut 	= 4
$borderSize = 1
$rounding 	= 8

# Animation toggle
# 1 = true, 0 = false, Turn off to save CPU
$enableAnimations	= 1
$enableBlur		= 0
$enableDropShadows 	= 0
