input {
    kb_layout = us

    follow_mouse = 1
    kb_variant = 
    kb_model =
    kb_options =
    kb_rules = 

    touchpad {
        natural_scroll = true
        tap-to-click = true
        disable_while_typing = true
    }

    sensitivity = 0 # -1.0 to 1.0, 0 means no modification.
}

gesture {
    workspace_swipe = true # use three fingies
}

# Example per-device config (useful if a specific mouse needs tweaking)
# See https://wiki.hyprland.org/Configuring/Keywords/#per-device-input-configs for more