general {
    col.active_border = rgb(9079a3)
    gaps_in = 2
    gaps_out = 4
    border_size = 1
}

decoration {
    rounding = 5
    rounding_power = 2
    blur {
        enabled = 1
        size = 3
        passes = 1
    }
    active_opacity = 1
    inactive_opacity = 0.5
}