[main]
pad	= 10x10
font	= Hack:size=5

[cursor]
blink	= yes

[colors-dark]
alpha=1.0
alpha-mode=default # Can be `default`, `matching` or `all`
background=000000
foreground=ffffff
flash=7f7f00
flash-alpha=0.5

## Normal/regular colors (color palette 0-7)
regular0=242424  # black
regular1=f62b5a  # red
regular2=47b413  # green
regular3=e3c401  # yellow
regular4=24acd4  # blue 
regular5=f2affd  # magenta
regular6=13c299  # cyan
regular7=e6e6e6  # white
